version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ApiIntegracao-bema
    ports:
      - "3335:3335"
    volumes:
      - /sgs/api-integracao/ApiIntegracao-Bema/:/usr/src/app  # Montar código fonte local
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: always  # Reiniciar automaticamente o container se ele falhar
